name: Django CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'


      - name: verificar Django
        run: |
            python manage.py check



        
